/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

%{ C++
#include "nsTArray.h"
%}

[ref] native IntegerArray(nsTArray<uint32_t>);

[uuid(20a4a728-1371-4552-8c48-f094045bea43)]
interface nsISocketTransportSDT : nsISupports
{
  unsigned long openStream();
  void closeStream(in unsigned long streamId);
  void resetStream(in unsigned long streamId);
  void getStreamsReadyToRead(out IntegerArray streamIds);
  void setNextStreamToRead(in unsigned long streamId, out long status);
  void setNextStreamToWrite(in unsigned long streamId, out long status);
  bool streamCanWrite(in unsigned long streamId);
};
